[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "setuptools_scm[toml]>3.4"
]

build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/rexpy/version.py"

[tool.black]
line-length = 92
target-version = ["py36"]
